# Generated by Django 5.2.6 on 2025-10-21 20:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_company_owner'),
        ('storage', '0002_alter_storage_address_alter_storage_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='storage.storage')),
            ],
            options={
                'ordering': ['title'],
                'unique_together': {('storage', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('inn', models.CharField(max_length=12, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='company.company')),
            ],
            options={
                'ordering': ['title'],
                'unique_together': {('company', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='products.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supply_items', to='products.product')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.supply')),
            ],
            options={
                'unique_together': {('supply', 'product')},
            },
        ),
        migrations.AddField(
            model_name='supply',
            name='products',
            field=models.ManyToManyField(related_name='supplies', through='products.SupplyProduct', to='products.product'),
        ),
    ]
